# Default variables
authentication_output_dir : "{{ playbook_dir }}/files/{{ inventory_dir | basename }}"

# prepare export directory; become
authentication_output_become: false
# set group to this group, null to not do anything
authentication_output_export_group: null
# default mode.  Should probably set to something a bit more restrictive than this.
authentication_output_export_mode: '0755'
